
    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_01_CUSTOMER_SKSK_PHONE_NO AS LOCK ROW FOR ACCESS 
    SELECT TRIM(SK_PHONE_NO) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE SK_PHONE_NO IS NOT NULL AND SK_PHONE_NO <> ''
    GROUP BY 1;

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_01_CUSTOMER_SKSK_PHONE_NO AS LOCK ROW FOR ACCESS 
    SELECT REGEXP_REPLACE(SK_PHONE_NO, '[^0-9]', '', 1, 0) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE SK_PHONE_NO IS NOT NULL AND SK_PHONE_NO <> ''
    AND LENGTH(REGEXP_REPLACE(SK_PHONE_NO, '[^0-9]', '', 1, 0)) = 11
    GROUP BY 1;

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_01_CUSTOMER_SKSK_PHONE_NO AS LOCK ROW FOR ACCESS 
    SELECT TRIM(SK_PHONE_NO) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE SK_PHONE_NO IS NOT NULL AND SK_PHONE_NO <> ''
    GROUP BY 1;

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_01_CUSTOMER_SKSK_PHONE_NO AS LOCK ROW FOR ACCESS 
    SELECT REGEXP_REPLACE(MOBILE_NUMBER, '[^0-9]', '', 1, 0s) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE EMP_ID IS NOT NULL AND EMP_ID <> ''
    AND LENGTH(REGEXP_REPLACE(MOBILE_NUMBER, '[^0-9]', '', 1, 0)) = 11
    GROUP BY 1;
    

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_02_CUSTOMER_SKSK_ADDR AS LOCK ROW FOR ACCESS 
    SELECT TRIM(SK_ADDR) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE SK_ADDR IS NOT NULL AND SK_ADDR <> ''
    GROUP BY 1;

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_02_CUSTOMER_SKSK_ADDR AS LOCK ROW FOR ACCESS 
    SELECT REGEXP_REPLACE(SK_ADDR, '[^0-9]', '', 1, 0) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE SK_ADDR IS NOT NULL AND SK_ADDR <> ''
    AND LENGTH(REGEXP_REPLACE(SK_ADDR, '[^0-9]', '', 1, 0)) = 11
    GROUP BY 1;

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_02_CUSTOMER_SKSK_ADDR AS LOCK ROW FOR ACCESS 
    SELECT TRIM(SK_ADDR) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE SK_ADDR IS NOT NULL AND SK_ADDR <> ''
    GROUP BY 1;

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_02_CUSTOMER_SKSK_ADDR AS LOCK ROW FOR ACCESS 
    SELECT REGEXP_REPLACE(MOBILE_NUMBER, '[^0-9]', '', 1, 0s) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE EMP_ID IS NOT NULL AND EMP_ID <> ''
    AND LENGTH(REGEXP_REPLACE(MOBILE_NUMBER, '[^0-9]', '', 1, 0)) = 11
    GROUP BY 1;
    

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_03_CUSTOMER_SKSK_EMAIL AS LOCK ROW FOR ACCESS 
    SELECT TRIM(SK_EMAIL) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE SK_EMAIL IS NOT NULL AND SK_EMAIL <> ''
    GROUP BY 1;

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_03_CUSTOMER_SKSK_EMAIL AS LOCK ROW FOR ACCESS 
    SELECT REGEXP_REPLACE(SK_EMAIL, '[^0-9]', '', 1, 0) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE SK_EMAIL IS NOT NULL AND SK_EMAIL <> ''
    AND LENGTH(REGEXP_REPLACE(SK_EMAIL, '[^0-9]', '', 1, 0)) = 11
    GROUP BY 1;

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_03_CUSTOMER_SKSK_EMAIL AS LOCK ROW FOR ACCESS 
    SELECT TRIM(SK_EMAIL) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE SK_EMAIL IS NOT NULL AND SK_EMAIL <> ''
    GROUP BY 1;

    REPLACE VIEW GDEV1V_INP.BK_LOCTR_LOCTR_ID_03_CUSTOMER_SKSK_EMAIL AS LOCK ROW FOR ACCESS 
    SELECT REGEXP_REPLACE(MOBILE_NUMBER, '[^0-9]', '', 1, 0s) AS SOURCE_KEY
    FROM GDEV1V_INP.CUSTOMER
    WHERE EMP_ID IS NOT NULL AND EMP_ID <> ''
    AND LENGTH(REGEXP_REPLACE(MOBILE_NUMBER, '[^0-9]', '', 1, 0)) = 11
    GROUP BY 1;
    